# config file for automatic testing at travis-ci.org
language: python
cache: pip

before_install:
    sudo apt-get install -y python3-dev

install:
  - pip install --upgrade pip setuptools
  - pip install virtualenv tox

script: tox -v

matrix:
  include:

  - python: "3.6"
    env: TOXENV=checks

  - python: "3.5"
    env: TOXENV=py35

  - python: "3.6"
    env: TOXENV=py36

  - python: "3.7"
    dist: xenial
    env: TOXENV=py37

  - python: "3.8"
    dist: bionic
    env: TOXENV=py38

  - python: "nightly"
    dist: bionic
    env: TOXENV=py39

  - python: "pypy3"
    env: TOXENV=pypy
